# Generated by Django 3.2.4 on 2021-06-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('videoid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('thumbnail_url', models.TextField()),
                ('publishedAt', models.DateTimeField()),
            ],
        ),
    ]
